// <auto-generated />
using MVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MVC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220530113435_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MVC.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Stockholm",
                            Name = "Johan Svensson",
                            PhoneNumber = "+46725180302"
                        },
                        new
                        {
                            Id = 2,
                            City = "Göteborg",
                            Name = "Nils Kristiansson",
                            PhoneNumber = "+46737470353"
                        },
                        new
                        {
                            Id = 3,
                            City = "Malmö",
                            Name = "Christoffer Nilsson",
                            PhoneNumber = "+46736395900"
                        },
                        new
                        {
                            Id = 4,
                            City = "Helsingfors",
                            Name = "Pekka Heino",
                            PhoneNumber = "+46725180305"
                        },
                        new
                        {
                            Id = 5,
                            City = "Köpenhamn",
                            Name = "Peter Rohde",
                            PhoneNumber = "+46733080322"
                        },
                        new
                        {
                            Id = 6,
                            City = "Berlin",
                            Name = "Lisa Braun",
                            PhoneNumber = "+46718180309"
                        },
                        new
                        {
                            Id = 7,
                            City = "Paris",
                            Name = "Blanche Berthelot",
                            PhoneNumber = "+46739470303"
                        },
                        new
                        {
                            Id = 8,
                            City = "Madrid",
                            Name = "Diego Garcia",
                            PhoneNumber = "+46739165309"
                        },
                        new
                        {
                            Id = 9,
                            City = "Stockholm",
                            Name = "Per Persson",
                            PhoneNumber = "+46739145209"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
